# Generated by Django 4.1.1 on 2022-11-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
